server:
  port: 8080

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: portfolio-service
              uri: http://localhost:8081
              predicates:
                - Path=/api/portfolios/**

            - id: transaction-service
              uri: http://localhost:8081
              predicates:
                - Path=/api/transactions/**

            - id: security-service
              uri: http://localhost:8081
              predicates:
                - Path=/api/securities/**