server:
  port: 8080

logging:
  level:
    org.springframework.cloud.gateway: INFO
    org.springframework.security: INFO
    org.springframework.data.redis: WARN

jwt:
  secret: ${JWT_SECRET}
  expiration: 900000

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:

            - id: auth-service
              uri: ${BACKEND_BASE_URL:http://localhost:8081}
              predicates:
                - Path=/api/auth/**

            - id: portfolio-service
              uri: ${BACKEND_BASE_URL:http://localhost:8081}
              predicates:
                - Path=/api/portfolios/**

            - id: transaction-service
              uri: ${BACKEND_BASE_URL:http://localhost:8081}
              predicates:
                - Path=/api/transactions/**

            - id: security-service
              uri: ${BACKEND_BASE_URL:http://localhost:8081}
              predicates:
                - Path=/api/securities/**
            - id: holding-service
              uri: ${BACKEND_BASE_URL:http://localhost:8081}
              predicates:
                - Path=/api/holdings/**
  data:
    redis:
      host:  ${REDIS_HOST:localhost}
      port:  ${REDIS_PORT:6379}